name: build image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo $CR_PAT | docker login ghcr.io -u maxkueng --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ghcr.io/maxkueng/flicd:latest \
            --platform linux/arm/v7 .
